### ISSUE TITLE
Missing parenthesis in call to print!

### ISSUE THREAD

**Issue by adriandeveloper** [riteshpradhan/udacity-dl#5]
Was trying this out. Recieved this error. 

`udacity-dl -h
Traceback (most recent call last):
  File "/usr/local/bin/udacity-dl", line 7, in <module>
    from udacitydl.udacitydl import main
  File "/usr/local/lib/python3.5/site-packages/udacitydl/udacitydl.py", line 37
    print "* Collecting downloadable content from " + course_url
                                                  ^
SyntaxError: Missing parentheses in call to 'print'`

This happens when both trying to view the help documentation and downloading a course.

**Comment by riteshpradhan** [comment]
This is expected. 
It is clear in README that it works with python 2.7. So currently it doesn't work with python 3 or greater. Need to update to work with current python version.
